import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "@/lib/types/database";
import type { EvidenceConflict, EvidenceGap, UUID } from "@/lib/types/domain";
import type { DetectedConflictSchema, DetectedGapSchema } from "@/lib/types/schemas";
import type { z } from "zod";

type ConflictRow = Database["public"]["Tables"]["evidence_conflicts"]["Row"];
type GapRow = Database["public"]["Tables"]["evidence_gaps"]["Row"];

type DetectedConflict = z.infer<typeof DetectedConflictSchema>;
type DetectedGap = z.infer<typeof DetectedGapSchema>;

function conflictToDomain(row: ConflictRow): EvidenceConflict {
  return {
    id: row.id,
    hypothesisId: row.hypothesis_id,
    conflictType: row.conflict_type as EvidenceConflict["conflictType"],
    severity: row.severity,
    description: row.description,
    supportingEvidenceIds: row.supporting_evidence_ids,
    contradictingEvidenceIds: row.contradicting_evidence_ids,
    status: row.status,
    autoGenerated: row.auto_generated,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

function gapToDomain(row: GapRow): EvidenceGap {
  return {
    id: row.id,
    hypothesisId: row.hypothesis_id,
    evidenceRequirementId: row.evidence_requirement_id,
    gapType: row.gap_type as EvidenceGap["gapType"],
    severity: row.severity,
    missingRequirement: row.missing_requirement,
    importance: row.importance,
    businessImpact: row.business_impact,
    recommendedValidation: row.recommended_validation,
    status: row.status,
    autoGenerated: row.auto_generated,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

export class ConflictGapRepository {
  constructor(private readonly db: SupabaseClient<Database>) {}

  async createConflicts(conflicts: DetectedConflict[]): Promise<EvidenceConflict[]> {
    if (conflicts.length === 0) return [];
    const rows = conflicts.map((c) => ({
      hypothesis_id: c.hypothesisId,
      conflict_type: c.conflictType,
      severity: c.severity,
      description: c.description,
      supporting_evidence_ids: c.supportingEvidenceIds,
      contradicting_evidence_ids: c.contradictingEvidenceIds,
      status: "open" as const,
      auto_generated: true,
    }));
    const { data, error } = await this.db.from("evidence_conflicts").insert(rows).select();
    if (error) throw error;
    return (data ?? []).map(conflictToDomain);
  }

  async createGaps(gaps: DetectedGap[]): Promise<EvidenceGap[]> {
    if (gaps.length === 0) return [];
    const rows = gaps.map((g) => ({
      hypothesis_id: g.hypothesisId,
      evidence_requirement_id: g.evidenceRequirementId ?? null,
      gap_type: g.gapType,
      severity: g.severity,
      missing_requirement: g.missingRequirement,
      importance: g.importance,
      business_impact: g.businessImpact,
      recommended_validation: g.recommendedValidation,
      status: "open" as const,
      auto_generated: true,
    }));
    const { data, error } = await this.db.from("evidence_gaps").insert(rows).select();
    if (error) throw error;
    return (data ?? []).map(gapToDomain);
  }

  async listConflictsByHypothesis(hypothesisId: UUID): Promise<EvidenceConflict[]> {
    const { data, error } = await this.db
      .from("evidence_conflicts")
      .select()
      .eq("hypothesis_id", hypothesisId);
    if (error) throw error;
    return (data ?? []).map(conflictToDomain);
  }

  async listConflictsByHypotheses(hypothesisIds: UUID[]): Promise<EvidenceConflict[]> {
    if (hypothesisIds.length === 0) return [];
    const { data, error } = await this.db
      .from("evidence_conflicts")
      .select()
      .in("hypothesis_id", hypothesisIds);
    if (error) throw error;
    return (data ?? []).map(conflictToDomain);
  }

  async listGapsByHypothesis(hypothesisId: UUID): Promise<EvidenceGap[]> {
    const { data, error } = await this.db
      .from("evidence_gaps")
      .select()
      .eq("hypothesis_id", hypothesisId);
    if (error) throw error;
    return (data ?? []).map(gapToDomain);
  }

  async listGapsByHypotheses(hypothesisIds: UUID[]): Promise<EvidenceGap[]> {
    if (hypothesisIds.length === 0) return [];
    const { data, error } = await this.db
      .from("evidence_gaps")
      .select()
      .in("hypothesis_id", hypothesisIds);
    if (error) throw error;
    return (data ?? []).map(gapToDomain);
  }

  /**
   * Re-evaluation ("Re-evaluate Evidence", Phase 4 Step 14) replaces the
   * previously auto-generated, still-open gaps/conflicts for a hypothesis
   * rather than accumulating duplicates on every run. Anything a founder
   * has already moved to reviewed/resolved (or manually annotated) is
   * left untouched — re-evaluation must never silently discard a human
   * review decision.
   */
  async deleteAutoGeneratedOpenConflicts(hypothesisId: UUID): Promise<void> {
    const { error } = await this.db
      .from("evidence_conflicts")
      .delete()
      .eq("hypothesis_id", hypothesisId)
      .eq("status", "open")
      .eq("auto_generated", true);
    if (error) throw error;
  }

  async deleteAutoGeneratedOpenGaps(hypothesisId: UUID): Promise<void> {
    const { error } = await this.db
      .from("evidence_gaps")
      .delete()
      .eq("hypothesis_id", hypothesisId)
      .eq("status", "open")
      .eq("auto_generated", true);
    if (error) throw error;
  }

  async updateConflictStatus(
    id: UUID,
    status: EvidenceConflict["status"],
  ): Promise<EvidenceConflict> {
    const { data, error } = await this.db
      .from("evidence_conflicts")
      .update({ status })
      .eq("id", id)
      .select()
      .single();
    if (error) throw error;
    return conflictToDomain(data);
  }

  async updateGapStatus(id: UUID, status: EvidenceGap["status"]): Promise<EvidenceGap> {
    const { data, error } = await this.db
      .from("evidence_gaps")
      .update({ status })
      .eq("id", id)
      .select()
      .single();
    if (error) throw error;
    return gapToDomain(data);
  }
}
